spring.application.name=tailor
server.servlet.context-path=/tailor
spring.profiles.active=prod


aws.region=ap-south-1
aws.s3.bucket-name=rs-tailor
aws.s3.base-url=https://rs-tailor.s3.ap-south-1.amazonaws.com


app.jwt.validity-period=86400000
app.jwt.secret=cf83e1357eefb8bdf1542850d6623434343434343434343434343434sdgdsgdg34535fsdfds3453af927da3e
app.jwt.issuer=epan007